### ISSUE TITLE
[Bug] Container fails to start due to malformed TCP address in Kubernetes deployment

### ISSUE THREAD

**Issue by LoneExile** [danvergara/morphos#83]
**Describe the bug**
Getting error when deploying morphos-server on Kubernetes cluster: `error listening and serving: listen tcp: address :tcp://10.43.193.138:8080: too many colons in address`

![image](https://github.com/user-attachments/assets/b8d5bf9e-8cab-480c-9fe1-96671c5ed2dd)

The container fails to start due to an invalid address format in the TCP listening configuration.

**To Reproduce**
1. Set up Kubernetes cluster on Rockchip ARM64 device with Armbian OS
2. Deploy RKE2 with Cilium CNI
3. Apply the following Kubernetes manifests:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: morphos-service
  labels:
    app: morphos
spec:
  selector:
    app: morphos
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: morphos-deployment
  labels:
    app: morphos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: morphos
  template:
    metadata:
      labels:
        app: morphos
    spec:
      containers:
        - name: morphos
          image: ghcr.io/danvergara/morphos-server:latest
          ports:
            - containerPort: 8080
```
4. Check pod logs: `kubectl logs morphos-758df6dccf-wptmm`

**Expected behavior**
The morphos-server container should start successfully and listen on port 8080.

**System Information:**
- OS: Armbian 24.11.2 noble
- Kernel: Linux 6.1.75-vendor-rk35xx
- Architecture: arm64
- Kubernetes: RKE2 with Cilium CNI

**Additional context**
The error seems to be related to how the server is trying to bind to the network interface. The address format `:tcp://10.43.193.138:8080` appears to be malformed, as it contains both a protocol prefix and a colon separator which is invalid for TCP address binding.

**Comment by danvergara** [comment]
Try this out:

```yaml
  ## on the deployment
  ports:
    - name: http
       containerPort: 8080
       protocol: TCP
```

```yml
  ## on the service
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
```

**Comment by LoneExile** [comment]
It worked! Thank you.

**Comment by fcarucci** [comment]
I have the same issue but the proposed fix didn't work for me, any idea what I could be doing wrong?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: morphos
  namespace: apps
  labels:
    app: morphos
  annotations:
    keel.sh/policy: all
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 60m"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: morphos
  template:
    metadata:
      labels:
        app: morphos
    spec:
      containers:
        - name: morphos
          image: harbor.k.carucci.studio/ghcr/danvergara/morphos-server:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "10m"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 60
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: morphos
  namespace: apps
  labels:
    app: morphos
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: morphos
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: morphos
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`morphos.example.com`)
      kind: Rule
      services:
        - name: morphos
          port: 80

```

**Comment by Blintmester** [comment]
@fcarucci I had the same issue, and found the solution, you have to set the `MORPHOS_PORT` env var:

```yaml
env:
            - name: MORPHOS_PORT
              value: "8080"
```

and the whole deployment:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: morphos
  namespace: apps
spec:
  selector:
    matchLabels:
      app: morphos
  template:
    metadata:
      labels:
        app: morphos
    spec:
      containers:
        - name: morphos
          image: ghcr.io/danvergara/morphos-server:0.6.0
          env:
            - name: MORPHOS_PORT
              value: "8080"
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 60
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      volumes:
            - name: tmp
              emptyDir: {}
```
